# <font color="#FFA500">VICTIMAS DIGITALES: ANÁLISIS DE LOS DELITOS INFORMÁTICOS EN COLOMBIA</font>

##1.1 Cargar librerias y bases

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import datetime
import seaborn as sns
from scipy.stats import chi2_contingency
from scipy.stats import f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.tsa.stattools import grangercausalitytests
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

In [2]:
#nueva base filtrada de 30M
#https://drive.google.com/file/d/1coDof8AiFvddDpMyjDN0N7uOl_FggX7y/view?usp=sharing

file_id = '1coDof8AiFvddDpMyjDN0N7uOl_FggX7y'
url = f'https://drive.google.com/uc?id={file_id}'
di = pd.read_csv(url)
di.head()

,Unnamed: 0,CRIMINALIDAD,ES_ARCHIVO,ES_PRECLUSIÓN,ESTADO,ETAPA_CASO,LEY,PAÍS_HECHO,DEPARTAMENTO_HECHO,MUNICIPIO_HECHO,...,GRUPO_DELITO,VÍCTIMA_CONSUMADO,SEXO,GRUPO_ETARIO,PAÍS_NACIMIENTO,APLICA_LGBTI,APLICA_NNA,INDÍGENA,AFRODESCENDIENTE,TOTAL_VÍCTIMAS
0,8,SI,NO,NO,ACTIVO,JUICIO,Ley 906,Colombia,Atlántico,BARRANQUILLA,...,DELITOS INFORMATICOS,NO APLICA,FEMENINO,Adulto entre 27 y 59 años.,Colombia,NO,NO,NO,NO,189
1,20,NO,SI,NO,INACTIVO,INDAGACIÓN,Ley 906,Colombia,Antioquia,BELLO,...,DELITOS INFORMATICOS,NO APLICA,MASCULINO,Adolescente de 14 a 17 años.,SIN DATO,NO,SI,NO,NO,1
2,24,SI,NO,NO,ACTIVO,INDAGACIÓN,Ley 906,Colombia,"BOGOTÁ, D. C.","BOGOTÁ, D.C.",...,DELITOS INFORMATICOS,NO APLICA,MASCULINO,Adulto entre 27 y 59 años.,Colombia,NO,NO,NO,NO,175
3,41,SI,SI,NO,INACTIVO,INDAGACIÓN,Ley 906,Colombia,Córdoba,CERETÉ,...,DELITOS INFORMATICOS,NO APLICA,FEMENINO,Adulto entre 27 y 59 años.,Colombia,NO,NO,NO,NO,2
4,74,SI,SI,NO,INACTIVO,INDAGACIÓN,Ley 906,Colombia,Antioquia,ENVIGADO,...,DELITOS INFORMATICOS,NO APLICA,FEMENINO,Adulto entre 27 y 59 años.,Colombia,NO,NO,NO,NO,36

##1.2 Conocer información básica

In [3]:
# Encontrar número de filas y columnas
di.shape

(105736, 25)

In [4]:
# Conocer información básica del Dataset
di.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105736 entries, 0 to 105735
Data columns (total 25 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Unnamed: 0          105736 non-null  int64
 1   CRIMINALIDAD        105736 non-null  object
 2   ES_ARCHIVO          105736 non-null  object
 3   ES_PRECLUSIÓN       105736 non-null  object
 4   ESTADO              105736 non-null  object
 5   ETAPA_CASO          105736 non-null  object
 6   LEY                 105736 non-null  object
 7   PAÍS_HECHO          105736 non-null  object
 8   DEPARTAMENTO_HECHO  105736 non-null  object
 9   MUNICIPIO_HECHO     105736 non-null  object
 10  SECCIONAL           105736 non-null  object
 11  AÑO_HECHOS          105736 non-null  int64
 12  AÑO_ENTRADA         105736 non-null  object
 13  AÑO_DENUNCIA        105736 non-null  object
 14  DELITO              105736 non-null  object
 15  GRUPO_DELITO        105736 non-null  object
 16  VÍCTIMA_CONSUMADO   105736 non-null  object
 17  SEXO                105736 non-null  object
 18  GRUPO_ETARIO        105736 non-null  object
 19  PAÍS_NACIMIENTO     105736 non-null  object
 20  APLICA_LGBTI        105736 non-null  object
 21  APLICA_NNA          105736 non-null  object
 22  INDÍGENA            105736 non-null  object
 23  AFRODESCENDIENTE    105736 non-null  object
 24  TOTAL_VÍCTIMAS      105736 non-null  int64
dtypes: int64(3), object(22)
memory usage: 20.2+ MB

In [5]:
# Reconocer los nombres de las columnas
di.columns

Index(['Unnamed: 0', 'CRIMINALIDAD', 'ES_ARCHIVO', 'ES_PRECLUSIÓN', 'ESTADO',
       'ETAPA_CASO', 'LEY', 'PAÍS_HECHO', 'DEPARTAMENTO_HECHO',
       'MUNICIPIO_HECHO', 'SECCIONAL', 'AÑO_HECHOS', 'AÑO_ENTRADA',
       'AÑO_DENUNCIA', 'DELITO', 'GRUPO_DELITO', 'VÍCTIMA_CONSUMADO', 'SEXO',
       'GRUPO_ETARIO', 'PAÍS_NACIMIENTO', 'APLICA_LGBTI', 'APLICA_NNA',
       'INDÍGENA', 'AFRODESCENDIENTE', 'TOTAL_VÍCTIMAS'],
      dtype='object')

In [6]:
# Número total de víctimas
print(di["TOTAL_VÍCTIMAS"].sum())

419907

In [7]:
# Número total de víctimas discrimadas por sexo. Tipo de datos: Numérico
di.groupby("SEXO")["TOTAL_VÍCTIMAS"].sum().sort_values()

SEXO
SIN DATO      23080
MASCULINO    178729
FEMENINO     218098
Name: TOTAL_VÍCTIMAS, dtype: int64

In [8]:
# Número total de víctimas discriminadas por grupo etario. Tipo de datos: Numérico
di.groupby("GRUPO_ETARIO")["TOTAL_VÍCTIMAS"].sum().sort_values()

GRUPO_ETARIO
Niño, Niña. Población de 0 a 13 años.                1608
Adolescente de 14 a 17 años.                         3285
Joven de 18 a 26 años.                              53799
Adulto mayor. Personas igual o mayor a 60 años.     56048
SIN DATO                                            64280
Adulto entre 27 y 59 años.                         240887
Name: TOTAL_VÍCTIMAS, dtype: int64

In [11]:
# Calcular el total de víctimas para sacar los porcentajes de los SIN DATO
di_total_victimas = di['TOTAL_VÍCTIMAS'].sum()

por_sexo = ( di.groupby("SEXO")["TOTAL_VÍCTIMAS"].sum().sort_values(ascending=False).reset_index())

# Agregar columna de porcentaje
por_sexo['PORCENTAJE'] = (por_sexo['TOTAL_VÍCTIMAS'] / di_total_victimas * 100).round(2)

# Mostrar resultados
por_sexo

        SEXO  TOTAL_VÍCTIMAS  PORCENTAJE
0   FEMENINO          218098       51.94
1  MASCULINO          178729       42.56
2   SIN DATO           23080        5.50

In [12]:
por_edad = ( di.groupby("GRUPO_ETARIO")["TOTAL_VÍCTIMAS"].sum().sort_values(ascending=False).reset_index())

# Agregar columna de porcentaje
por_edad['PORCENTAJE'] = (por_edad['TOTAL_VÍCTIMAS'] / di_total_victimas * 100).round(2)

# Mostrar resultados
por_edad

                                      GRUPO_ETARIO  TOTAL_VÍCTIMAS  PORCENTAJE
0                       Adulto entre 27 y 59 años.          240887       57.37
1                                         SIN DATO           64280       15.31
2  Adulto mayor. Personas igual o mayor a 60 años.           56048       13.35
3                           Joven de 18 a 26 años.           53799       12.81
4                     Adolescente de 14 a 17 años.            3285        0.78
5            Niño, Niña. Población de 0 a 13 años.            1608        0.38

In [13]:
# Generar informe YData
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.15.2)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.11.3)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.0.2)
Collecting htmlmin==0.1.12 (from ydata-profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting phik<0.13,>=0.11.1 (from ydata-profiling)
  Downloading phik-0.12.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.24.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.14.4)
Requirement already satisfied: typeguard<5,>=3 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.4.2)
Collecting imagehash==4.3.1 (from ydata-profiling)
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: wordcloud>=1.9.3 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.9.4)
Collecting dacite>=1.8 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.60.0)
Collecting PyWavelets (from imagehash==4.3.1->ydata-profiling)
  Downloading pywavelets-1.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from imagehash==4.3.1->ydata-profiling) (11.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.11/dist-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (2.33.1)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (4.13.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2025.4.26)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.4.2)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-1.28-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.1/400.1 kB 9.1 MB/s eta 0:00:00
Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 29.3 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (687 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 687.8/687.8 kB 32.4 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 9.8 MB/s eta 0:00:00
Downloading puremagic-1.28-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.2/43.2 kB 3.9 MB/s eta 0:00:00
Downloading pywavelets-1.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 93.5 MB/s eta 0:00:00
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (setup.py) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=0219fb20715c2ffa66c46fcca11ffa1c49f507650040201f61a650c4a6b778f8
  Stored in directory: /root/.cache/pip/wheels/8d/55/1a/19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin
Installing collected packages: puremagic, htmlmin, PyWavelets, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed PyWavelets-1.8.0 dacite-1.9.2 htmlmin-0.1.12 imagehash-4.3.1 multimethod-1.12 phik-0.12.4 puremagic-1.28 visions-0.8.1 ydata-profiling-4.16.1

In [14]:
# Generar informe YData
from ydata_profiling import ProfileReport

profile = ProfileReport (di, title= "Reporte de EDA", explorative = True)

profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/25 [00:00<?, ?it/s]
  4%|▍         | 1/25 [00:00<00:16,  1.46it/s]
 24%|██▍       | 6/25 [00:00<00:02,  7.82it/s]
 32%|███▏      | 8/25 [00:01<00:02,  7.63it/s]
 40%|████      | 10/25 [00:01<00:02,  6.84it/s]
 52%|█████▏    | 13/25 [00:01<00:01,  8.21it/s]
 60%|██████    | 15/25 [00:02<00:01,  6.52it/s]
 72%|███████▏  | 18/25 [00:02<00:00,  7.42it/s]
 76%|███████▌  | 19/25 [00:02<00:00,  6.89it/s]
 80%|████████  | 20/25 [00:03<00:00,  6.12it/s]
 84%|████████▍ | 21/25 [00:03<00:00,  5.97it/s]
 88%|████████▊ | 22/25 [00:03<00:00,  5.64it/s]
 92%|█████████▏| 23/25 [00:03<00:00,  5.66it/s]
100%|██████████| 25/25 [00:03<00:00,  6.64it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [16]:
#
por_dpto = ( di.groupby("DEPARTAMENTO_HECHO")["TOTAL_VÍCTIMAS"].sum().sort_values(ascending=False).reset_index())

# Agregar columna de porcentaje
por_dpto['PORCENTAJE'] = (por_edad['TOTAL_VÍCTIMAS'] / di_total_victimas * 100).round(2)

# Mostrar resultados
por_dpto

,DEPARTAMENTO_HECHO,TOTAL_VÍCTIMAS,PORCENTAJE
0,"BOGOTÁ, D. C.",94991,57.37
1,Antioquia,80207,15.31
2,Valle del Cauca,62129,13.35
3,Atlántico,26649,12.81
4,Cundinamarca,26078,0.78
5,Santander,12539,0.38
6,Tolima,11085,NaN
7,Norte de Santander,10216,NaN
8,Bolívar,9828,NaN
9,Risaralda,8964,NaN
10,Cauca,7835,NaN
11,Meta,7629,NaN
12,Córdoba,7281,NaN
13,Huila,7037,NaN
14,Magdalena,6401,NaN
15,Nariño,6257,NaN
16,Boyaca,6115,NaN
17,Caldas,5189,NaN
18,Quindío,4258,NaN
19,Cesar,3951,NaN
20,Sucre,3467,NaN
21,Caquetá,2487,NaN
22,Casanare,1997,NaN
23,Chocó,1965,NaN
24,La Guajira,1812,NaN
25,Arauca,958,NaN
26,Putumayo,950,NaN
27,Guaviare,596,NaN
28,SIN DATO,414,NaN
29,"Archipiélago de San Andrés, Providencia y Sant...",354,NaN
30,Amazonas,75,NaN
31,Guainía,74,NaN
32,Vichada,73,NaN
33,Vaupés,46,NaN

### Calcular medidas de tendencia central de las variables (sexo, edad, departamento)

---

Al tener la gran mayoría de nuestras variables categóricas estaremos calculando la moda como medida de tendencia central de las variables: **SEXO, EDAD, DEPARTAMENTO**

In [19]:
# Moda del sexo donde el sin dato es del 5.5%
di["SEXO"].mode()

0    FEMENINO
Name: SEXO, dtype: object

In [20]:
#Moda del GRUPO ETARIO donde el sin dato es del 15.3%
di["GRUPO_ETARIO"].mode()

0    Adulto entre 27 y 59 años.
Name: GRUPO_ETARIO, dtype: object

In [18]:
# Moda del sexo donde el sin dato es del 5.5%
di["DEPARTAMENTO_HECHO"].mode()

0    Antioquia
Name: DEPARTAMENTO_HECHO, dtype: object

In [24]:
import os
os.getcwd()

'/content'

In [30]:
# prompt: import nbformat
# path = 'content/Fase_filtrada_DI.ipynb'  # Update with the actual filename
# with open(path) as f:
#     nb = nbformat.read(f, as_version=4)
# # Remove widgets metadata
# if 'widgets' in nb['metadata']:
#     del nb['metadata']['widgets']
# with open(path, 'w') as f:
#     nbformat.write(nb, f)
# i need to use it on this notebook

import nbformat
import os

# Specify the correct path to your notebook file.
# Use os.path.join for platform-independent path construction.
path = os.path.join(os.getcwd(), 'Fase_filtrada_DI.ipynb')

# Check if the file exists before attempting to open it
if os.path.exists(path):
    with open(path) as f:
        nb = nbformat.read(f, as_version=4)

    # Remove widgets metadata
    if 'widgets' in nb['metadata']:
        del nb['metadata']['widgets']

    with open(path, 'w') as f:
        nbformat.write(nb, f)

    print(f"Successfully processed {path}")
else:
    print(f"Error: File not found at {path}")

Error: File not found at /content/Fase_filtrada_DI.ipynb

In [28]:
import nbformat

path = 'content/Fase_filtrada_DI.ipynb'  # Update with the actual filename

with open(path) as f:
    nb = nbformat.read(f, as_version=4)

# Remove widgets metadata
if 'widgets' in nb['metadata']:
    del nb['metadata']['widgets']

with open(path, 'w') as f:
    nbformat.write(nb, f)

FileNotFoundError: [Errno 2] No such file or directory: 'content/Fase_filtrada_DI.ipynb'

##1.3 Análisis de Datos EDA

##1.4 Limpieza y Preparación de Datos

##1.5 Análisis Inferencial

##1.6 Análisis Causal